## Part:1
#Question_1

In [2]:
import numpy as np

X = np.random.rand(10,3)
Y = np.random.rand(3)

#a. no error
X+Y 


array([[1.34312488, 0.91966184, 1.80550274],
       [1.76681287, 1.22852318, 1.56158052],
       [0.93728384, 0.85956838, 1.85267892],
       [1.56476984, 1.14642506, 1.66446915],
       [1.09013764, 1.13121595, 1.64186796],
       [0.99588293, 1.0553035 , 1.63357167],
       [0.83417869, 0.81434779, 1.81969226],
       [1.39732289, 0.30641944, 0.91953553],
       [1.59552832, 1.24776058, 1.02909044],
       [1.32325503, 0.40163216, 1.55600823]])

In [5]:
#b. no error
X[np.newaxis, :] + Y

array([[[0.91777969, 0.60663692, 1.51007542],
        [1.66275464, 0.58597491, 1.07604344],
        [1.49707076, 0.62328514, 0.64724245],
        [1.3639485 , 0.69684127, 0.67557653],
        [0.96239979, 0.88625179, 0.96644351],
        [1.57822568, 1.28476507, 0.61074854],
        [1.88095139, 0.65839816, 1.37690679],
        [1.00148116, 1.10182789, 1.48031742],
        [1.41509216, 0.51096511, 0.68717204],
        [1.6796643 , 1.29236157, 1.23479418]]])

In [6]:
#c. shape error
X + Y[: , np.newaxis]

ValueError: operands could not be broadcast together with shapes (10,3) (3,1) 

In [7]:
#d no error
X[:, np.newaxis] + Y

array([[[0.91777969, 0.60663692, 1.51007542]],

       [[1.66275464, 0.58597491, 1.07604344]],

       [[1.49707076, 0.62328514, 0.64724245]],

       [[1.3639485 , 0.69684127, 0.67557653]],

       [[0.96239979, 0.88625179, 0.96644351]],

       [[1.57822568, 1.28476507, 0.61074854]],

       [[1.88095139, 0.65839816, 1.37690679]],

       [[1.00148116, 1.10182789, 1.48031742]],

       [[1.41509216, 0.51096511, 0.68717204]],

       [[1.6796643 , 1.29236157, 1.23479418]]])

In [8]:
#e no error
X + Y[np.newaxis, :] 

array([[0.91777969, 0.60663692, 1.51007542],
       [1.66275464, 0.58597491, 1.07604344],
       [1.49707076, 0.62328514, 0.64724245],
       [1.3639485 , 0.69684127, 0.67557653],
       [0.96239979, 0.88625179, 0.96644351],
       [1.57822568, 1.28476507, 0.61074854],
       [1.88095139, 0.65839816, 1.37690679],
       [1.00148116, 1.10182789, 1.48031742],
       [1.41509216, 0.51096511, 0.68717204],
       [1.6796643 , 1.29236157, 1.23479418]])

In [9]:
#f no error
X[:, np.newaxis, :] + Y 

array([[[0.91777969, 0.60663692, 1.51007542]],

       [[1.66275464, 0.58597491, 1.07604344]],

       [[1.49707076, 0.62328514, 0.64724245]],

       [[1.3639485 , 0.69684127, 0.67557653]],

       [[0.96239979, 0.88625179, 0.96644351]],

       [[1.57822568, 1.28476507, 0.61074854]],

       [[1.88095139, 0.65839816, 1.37690679]],

       [[1.00148116, 1.10182789, 1.48031742]],

       [[1.41509216, 0.51096511, 0.68717204]],

       [[1.6796643 , 1.29236157, 1.23479418]]])

#Question_2

In [6]:
#a.
x, y = np.mgrid[:10, :5]
z = x + y 

print("x dim=", np.shape(x), "y dim=", np.shape(y),"z dim=", np.shape(z))


x dim= (10, 5) y dim= (10, 5) z dim= (10, 5)


In [8]:
#b.
x, y = np.ogrid[:10, :5]
z = x + y 

print("x dim=", np.shape(x), "y dim=", np.shape(y),"z dim=", np.shape(z))


x dim= (10, 1) y dim= (1, 5) z dim= (10, 5)


#Question_3