## Part:1
#Question_1

In [25]:
import numpy as np

X = np.random.rand(10,3)
Y = np.random.rand(3)

#a. no error
X+Y 


array([[1.12689478, 1.50081782, 1.47148662],
       [0.72289263, 1.39724897, 1.8606754 ],
       [0.97368715, 0.95287312, 0.92780761],
       [0.76150068, 1.02724922, 1.12391352],
       [0.75775648, 1.13687339, 1.89836913],
       [0.18948457, 1.37988112, 1.39628776],
       [1.01292789, 1.17042788, 1.70251544],
       [0.60159449, 1.67948488, 1.55867698],
       [0.47878161, 0.84707499, 1.37605627],
       [1.10599207, 1.19959814, 1.24237256]])

In [12]:
#b. no error
X[np.newaxis, :] + Y

array([[[0.84488626, 0.36177765, 0.41944857],
        [0.90958762, 0.53523148, 0.46112702],
        [1.12391967, 0.23516991, 1.27018522],
        [0.77443586, 0.48986889, 0.6928376 ],
        [0.70729222, 0.43833768, 0.51594339],
        [0.46407326, 0.87517884, 0.40738835],
        [0.59677761, 0.41432991, 1.1431438 ],
        [1.25025987, 0.96672416, 0.69504472],
        [1.20942973, 0.92611414, 1.20388057],
        [1.02656545, 0.44759901, 0.70636503]]])

In [8]:
#c. shape error
X + Y[: , np.newaxis]

ValueError: operands could not be broadcast together with shapes (10,3) (3,1) 

In [13]:
#d no error
X[:, np.newaxis] + Y

array([[[0.84488626, 0.36177765, 0.41944857]],

       [[0.90958762, 0.53523148, 0.46112702]],

       [[1.12391967, 0.23516991, 1.27018522]],

       [[0.77443586, 0.48986889, 0.6928376 ]],

       [[0.70729222, 0.43833768, 0.51594339]],

       [[0.46407326, 0.87517884, 0.40738835]],

       [[0.59677761, 0.41432991, 1.1431438 ]],

       [[1.25025987, 0.96672416, 0.69504472]],

       [[1.20942973, 0.92611414, 1.20388057]],

       [[1.02656545, 0.44759901, 0.70636503]]])

In [16]:
#e no error
X + Y[np.newaxis, :] 

array([[0.84488626, 0.36177765, 0.41944857],
       [0.90958762, 0.53523148, 0.46112702],
       [1.12391967, 0.23516991, 1.27018522],
       [0.77443586, 0.48986889, 0.6928376 ],
       [0.70729222, 0.43833768, 0.51594339],
       [0.46407326, 0.87517884, 0.40738835],
       [0.59677761, 0.41432991, 1.1431438 ],
       [1.25025987, 0.96672416, 0.69504472],
       [1.20942973, 0.92611414, 1.20388057],
       [1.02656545, 0.44759901, 0.70636503]])

In [17]:
#f no error
X[:, np.newaxis, :] + Y 

array([[[0.84488626, 0.36177765, 0.41944857]],

       [[0.90958762, 0.53523148, 0.46112702]],

       [[1.12391967, 0.23516991, 1.27018522]],

       [[0.77443586, 0.48986889, 0.6928376 ]],

       [[0.70729222, 0.43833768, 0.51594339]],

       [[0.46407326, 0.87517884, 0.40738835]],

       [[0.59677761, 0.41432991, 1.1431438 ]],

       [[1.25025987, 0.96672416, 0.69504472]],

       [[1.20942973, 0.92611414, 1.20388057]],

       [[1.02656545, 0.44759901, 0.70636503]]])

In [20]:
x, y = np.mgrid[:10, :5]
z = x + y 

print(np.shape(x), np.shape(y), np.shape(z))


(10, 5) (10, 5) (10, 5)
