In [11]:
import numpy as np

X = np.random.rand(10,3)
Y = np.random.rand(3)

#a. no error
X+Y 


array([[0.84488626, 0.36177765, 0.41944857],
       [0.90958762, 0.53523148, 0.46112702],
       [1.12391967, 0.23516991, 1.27018522],
       [0.77443586, 0.48986889, 0.6928376 ],
       [0.70729222, 0.43833768, 0.51594339],
       [0.46407326, 0.87517884, 0.40738835],
       [0.59677761, 0.41432991, 1.1431438 ],
       [1.25025987, 0.96672416, 0.69504472],
       [1.20942973, 0.92611414, 1.20388057],
       [1.02656545, 0.44759901, 0.70636503]])

In [12]:
#b. no error
X[np.newaxis, :] + Y

array([[[0.84488626, 0.36177765, 0.41944857],
        [0.90958762, 0.53523148, 0.46112702],
        [1.12391967, 0.23516991, 1.27018522],
        [0.77443586, 0.48986889, 0.6928376 ],
        [0.70729222, 0.43833768, 0.51594339],
        [0.46407326, 0.87517884, 0.40738835],
        [0.59677761, 0.41432991, 1.1431438 ],
        [1.25025987, 0.96672416, 0.69504472],
        [1.20942973, 0.92611414, 1.20388057],
        [1.02656545, 0.44759901, 0.70636503]]])

In [8]:
#c. shape error
X + Y[: , np.newaxis]

ValueError: operands could not be broadcast together with shapes (10,3) (3,1) 

In [13]:
#d no error
X[:, np.newaxis] + Y

array([[[0.84488626, 0.36177765, 0.41944857]],

       [[0.90958762, 0.53523148, 0.46112702]],

       [[1.12391967, 0.23516991, 1.27018522]],

       [[0.77443586, 0.48986889, 0.6928376 ]],

       [[0.70729222, 0.43833768, 0.51594339]],

       [[0.46407326, 0.87517884, 0.40738835]],

       [[0.59677761, 0.41432991, 1.1431438 ]],

       [[1.25025987, 0.96672416, 0.69504472]],

       [[1.20942973, 0.92611414, 1.20388057]],

       [[1.02656545, 0.44759901, 0.70636503]]])

In [16]:
#e no error
X + Y[np.newaxis, :] 

array([[0.84488626, 0.36177765, 0.41944857],
       [0.90958762, 0.53523148, 0.46112702],
       [1.12391967, 0.23516991, 1.27018522],
       [0.77443586, 0.48986889, 0.6928376 ],
       [0.70729222, 0.43833768, 0.51594339],
       [0.46407326, 0.87517884, 0.40738835],
       [0.59677761, 0.41432991, 1.1431438 ],
       [1.25025987, 0.96672416, 0.69504472],
       [1.20942973, 0.92611414, 1.20388057],
       [1.02656545, 0.44759901, 0.70636503]])

In [17]:
#f no error
X[:, np.newaxis, :] + Y 

array([[[0.84488626, 0.36177765, 0.41944857]],

       [[0.90958762, 0.53523148, 0.46112702]],

       [[1.12391967, 0.23516991, 1.27018522]],

       [[0.77443586, 0.48986889, 0.6928376 ]],

       [[0.70729222, 0.43833768, 0.51594339]],

       [[0.46407326, 0.87517884, 0.40738835]],

       [[0.59677761, 0.41432991, 1.1431438 ]],

       [[1.25025987, 0.96672416, 0.69504472]],

       [[1.20942973, 0.92611414, 1.20388057]],

       [[1.02656545, 0.44759901, 0.70636503]]])