#Part:1
## Question_1

In [10]:
import numpy as np

X = np.random.rand(10,3)
Y = np.random.rand(3)

#a. no error
X+Y 


array([[1.07327335, 1.23710607, 1.36015744],
       [0.78146535, 1.32905802, 1.74554251],
       [0.95317242, 1.21721301, 1.14535236],
       [0.9317272 , 0.7265234 , 1.7489362 ],
       [1.29768347, 0.82683106, 1.65756426],
       [1.72988159, 1.05062619, 1.39508792],
       [1.39364395, 0.99609996, 1.36239465],
       [1.32896492, 0.41584073, 1.56753499],
       [1.55714456, 1.27603977, 1.54195351],
       [1.41884933, 1.159548  , 1.02127991]])

In [11]:
#b. no error
X[np.newaxis, :] + Y

array([[[1.07327335, 1.23710607, 1.36015744],
        [0.78146535, 1.32905802, 1.74554251],
        [0.95317242, 1.21721301, 1.14535236],
        [0.9317272 , 0.7265234 , 1.7489362 ],
        [1.29768347, 0.82683106, 1.65756426],
        [1.72988159, 1.05062619, 1.39508792],
        [1.39364395, 0.99609996, 1.36239465],
        [1.32896492, 0.41584073, 1.56753499],
        [1.55714456, 1.27603977, 1.54195351],
        [1.41884933, 1.159548  , 1.02127991]]])

In [12]:
#c. shape error
X + Y[: , np.newaxis]

ValueError: operands could not be broadcast together with shapes (10,3) (3,1) 

In [13]:
#d no error
X[:, np.newaxis] + Y

array([[[1.07327335, 1.23710607, 1.36015744]],

       [[0.78146535, 1.32905802, 1.74554251]],

       [[0.95317242, 1.21721301, 1.14535236]],

       [[0.9317272 , 0.7265234 , 1.7489362 ]],

       [[1.29768347, 0.82683106, 1.65756426]],

       [[1.72988159, 1.05062619, 1.39508792]],

       [[1.39364395, 0.99609996, 1.36239465]],

       [[1.32896492, 0.41584073, 1.56753499]],

       [[1.55714456, 1.27603977, 1.54195351]],

       [[1.41884933, 1.159548  , 1.02127991]]])

In [14]:
#e no error
X + Y[np.newaxis, :] 

array([[1.07327335, 1.23710607, 1.36015744],
       [0.78146535, 1.32905802, 1.74554251],
       [0.95317242, 1.21721301, 1.14535236],
       [0.9317272 , 0.7265234 , 1.7489362 ],
       [1.29768347, 0.82683106, 1.65756426],
       [1.72988159, 1.05062619, 1.39508792],
       [1.39364395, 0.99609996, 1.36239465],
       [1.32896492, 0.41584073, 1.56753499],
       [1.55714456, 1.27603977, 1.54195351],
       [1.41884933, 1.159548  , 1.02127991]])

In [15]:
#f no error
X[:, np.newaxis, :] + Y 

array([[[1.07327335, 1.23710607, 1.36015744]],

       [[0.78146535, 1.32905802, 1.74554251]],

       [[0.95317242, 1.21721301, 1.14535236]],

       [[0.9317272 , 0.7265234 , 1.7489362 ]],

       [[1.29768347, 0.82683106, 1.65756426]],

       [[1.72988159, 1.05062619, 1.39508792]],

       [[1.39364395, 0.99609996, 1.36239465]],

       [[1.32896492, 0.41584073, 1.56753499]],

       [[1.55714456, 1.27603977, 1.54195351]],

       [[1.41884933, 1.159548  , 1.02127991]]])

## Question_2

In [16]:
#a.
x, y = np.mgrid[:10, :5]
z = x + y 

print("x dim=", np.shape(x), "y dim=", np.shape(y),"z dim=", np.shape(z))


x dim= (10, 5) y dim= (10, 5) z dim= (10, 5)


In [17]:
#b.
x, y = np.ogrid[:10, :5]
z = x + y 

print("x dim=", np.shape(x), "y dim=", np.shape(y),"z dim=", np.shape(z))


x dim= (10, 1) y dim= (1, 5) z dim= (10, 5)


## Question_3

For np.ogrid only one dimension of each returned array is greater than 1.
And np.mgrid returns a dense mesh-grid when indexed, so that each returned argument has the same shape.

## Question_4

In [21]:
dist  =  np.array([0,  198,  303,  736,  871,  1175,  1475, 
1544, 1913, 2448])



array([   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448])

## Question_5

Q changed with operation on T due to the shallow copy. If we use deep copy then Q won't change if we alter T.

In [25]:
T = [[1, 2, 3], [ 4, 5, 6], [7, 8, 9]] 
Q = list(T) 
T[1][0] = 100000 

print("original:", T, Q)

import copy
T = [[1, 2, 3], [ 4, 5, 6], [7, 8, 9]] 
Q = copy.deepcopy(T) 
T[1][0] = 100000 

print("with deepcopy:", T, Q)

original: [[1, 2, 3], [100000, 5, 6], [7, 8, 9]] [[1, 2, 3], [100000, 5, 6], [7, 8, 9]]
with deepcopy: [[1, 2, 3], [100000, 5, 6], [7, 8, 9]] [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## Question_6

In [51]:
X = np.array([5, 9, 77, 0, 74, 55, 81, 79, 90]) 
Y = np.array([5, 1, 46, 2, 10, 29, 55, 4, 90]) 
#a
greater_idx= np.where(X>Y)[0]
greater_val= X[greater_idx]

print("greater_index:", greater_idx, "greater_value:", greater_val)

#b
eq = ((X==Y)*1)
eq_idx= np.where(eq==1)[0]
print("equal_index", eq_idx)

greater_index: [1 2 4 5 6 7] greater_value: [ 9 77 74 55 81 79]
equal_index [0 8]
