## Part:1
#Question_1

In [4]:
import numpy as np

X = np.random.rand(10,3)
Y = np.random.rand(3)

#a. no error
X+Y 


array([[0.91777969, 0.60663692, 1.51007542],
       [1.66275464, 0.58597491, 1.07604344],
       [1.49707076, 0.62328514, 0.64724245],
       [1.3639485 , 0.69684127, 0.67557653],
       [0.96239979, 0.88625179, 0.96644351],
       [1.57822568, 1.28476507, 0.61074854],
       [1.88095139, 0.65839816, 1.37690679],
       [1.00148116, 1.10182789, 1.48031742],
       [1.41509216, 0.51096511, 0.68717204],
       [1.6796643 , 1.29236157, 1.23479418]])

In [5]:
#b. no error
X[np.newaxis, :] + Y

array([[[0.91777969, 0.60663692, 1.51007542],
        [1.66275464, 0.58597491, 1.07604344],
        [1.49707076, 0.62328514, 0.64724245],
        [1.3639485 , 0.69684127, 0.67557653],
        [0.96239979, 0.88625179, 0.96644351],
        [1.57822568, 1.28476507, 0.61074854],
        [1.88095139, 0.65839816, 1.37690679],
        [1.00148116, 1.10182789, 1.48031742],
        [1.41509216, 0.51096511, 0.68717204],
        [1.6796643 , 1.29236157, 1.23479418]]])

In [6]:
#c. shape error
X + Y[: , np.newaxis]

ValueError: operands could not be broadcast together with shapes (10,3) (3,1) 

In [7]:
#d no error
X[:, np.newaxis] + Y

array([[[0.91777969, 0.60663692, 1.51007542]],

       [[1.66275464, 0.58597491, 1.07604344]],

       [[1.49707076, 0.62328514, 0.64724245]],

       [[1.3639485 , 0.69684127, 0.67557653]],

       [[0.96239979, 0.88625179, 0.96644351]],

       [[1.57822568, 1.28476507, 0.61074854]],

       [[1.88095139, 0.65839816, 1.37690679]],

       [[1.00148116, 1.10182789, 1.48031742]],

       [[1.41509216, 0.51096511, 0.68717204]],

       [[1.6796643 , 1.29236157, 1.23479418]]])

In [8]:
#e no error
X + Y[np.newaxis, :] 

array([[0.91777969, 0.60663692, 1.51007542],
       [1.66275464, 0.58597491, 1.07604344],
       [1.49707076, 0.62328514, 0.64724245],
       [1.3639485 , 0.69684127, 0.67557653],
       [0.96239979, 0.88625179, 0.96644351],
       [1.57822568, 1.28476507, 0.61074854],
       [1.88095139, 0.65839816, 1.37690679],
       [1.00148116, 1.10182789, 1.48031742],
       [1.41509216, 0.51096511, 0.68717204],
       [1.6796643 , 1.29236157, 1.23479418]])

In [9]:
#f no error
X[:, np.newaxis, :] + Y 

array([[[0.91777969, 0.60663692, 1.51007542]],

       [[1.66275464, 0.58597491, 1.07604344]],

       [[1.49707076, 0.62328514, 0.64724245]],

       [[1.3639485 , 0.69684127, 0.67557653]],

       [[0.96239979, 0.88625179, 0.96644351]],

       [[1.57822568, 1.28476507, 0.61074854]],

       [[1.88095139, 0.65839816, 1.37690679]],

       [[1.00148116, 1.10182789, 1.48031742]],

       [[1.41509216, 0.51096511, 0.68717204]],

       [[1.6796643 , 1.29236157, 1.23479418]]])

In [15]:
x, y = np.mgrid[:10, :5]
z = x + y 

print(np.shape(x), np.shape(y), np.shape(z))
z

(10, 5) (10, 5) (10, 5)


array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]])

In [11]:
x, y = np.ogrid[:10, :5]
z = x + y 

print(np.shape(x), np.shape(y), np.shape(z))


(10, 1) (1, 5) (10, 5)
