## Part:1
#Question_1

In [10]:
import numpy as np

X = np.random.rand(10,3)
Y = np.random.rand(3)

#a. no error
X+Y 


array([[1.07327335, 1.23710607, 1.36015744],
       [0.78146535, 1.32905802, 1.74554251],
       [0.95317242, 1.21721301, 1.14535236],
       [0.9317272 , 0.7265234 , 1.7489362 ],
       [1.29768347, 0.82683106, 1.65756426],
       [1.72988159, 1.05062619, 1.39508792],
       [1.39364395, 0.99609996, 1.36239465],
       [1.32896492, 0.41584073, 1.56753499],
       [1.55714456, 1.27603977, 1.54195351],
       [1.41884933, 1.159548  , 1.02127991]])

In [11]:
#b. no error
X[np.newaxis, :] + Y

array([[[1.07327335, 1.23710607, 1.36015744],
        [0.78146535, 1.32905802, 1.74554251],
        [0.95317242, 1.21721301, 1.14535236],
        [0.9317272 , 0.7265234 , 1.7489362 ],
        [1.29768347, 0.82683106, 1.65756426],
        [1.72988159, 1.05062619, 1.39508792],
        [1.39364395, 0.99609996, 1.36239465],
        [1.32896492, 0.41584073, 1.56753499],
        [1.55714456, 1.27603977, 1.54195351],
        [1.41884933, 1.159548  , 1.02127991]]])

In [12]:
#c. shape error
X + Y[: , np.newaxis]

ValueError: operands could not be broadcast together with shapes (10,3) (3,1) 

In [13]:
#d no error
X[:, np.newaxis] + Y

array([[[1.07327335, 1.23710607, 1.36015744]],

       [[0.78146535, 1.32905802, 1.74554251]],

       [[0.95317242, 1.21721301, 1.14535236]],

       [[0.9317272 , 0.7265234 , 1.7489362 ]],

       [[1.29768347, 0.82683106, 1.65756426]],

       [[1.72988159, 1.05062619, 1.39508792]],

       [[1.39364395, 0.99609996, 1.36239465]],

       [[1.32896492, 0.41584073, 1.56753499]],

       [[1.55714456, 1.27603977, 1.54195351]],

       [[1.41884933, 1.159548  , 1.02127991]]])

In [14]:
#e no error
X + Y[np.newaxis, :] 

array([[1.07327335, 1.23710607, 1.36015744],
       [0.78146535, 1.32905802, 1.74554251],
       [0.95317242, 1.21721301, 1.14535236],
       [0.9317272 , 0.7265234 , 1.7489362 ],
       [1.29768347, 0.82683106, 1.65756426],
       [1.72988159, 1.05062619, 1.39508792],
       [1.39364395, 0.99609996, 1.36239465],
       [1.32896492, 0.41584073, 1.56753499],
       [1.55714456, 1.27603977, 1.54195351],
       [1.41884933, 1.159548  , 1.02127991]])

In [15]:
#f no error
X[:, np.newaxis, :] + Y 

array([[[1.07327335, 1.23710607, 1.36015744]],

       [[0.78146535, 1.32905802, 1.74554251]],

       [[0.95317242, 1.21721301, 1.14535236]],

       [[0.9317272 , 0.7265234 , 1.7489362 ]],

       [[1.29768347, 0.82683106, 1.65756426]],

       [[1.72988159, 1.05062619, 1.39508792]],

       [[1.39364395, 0.99609996, 1.36239465]],

       [[1.32896492, 0.41584073, 1.56753499]],

       [[1.55714456, 1.27603977, 1.54195351]],

       [[1.41884933, 1.159548  , 1.02127991]]])

#Question_2

In [16]:
#a.
x, y = np.mgrid[:10, :5]
z = x + y 

print("x dim=", np.shape(x), "y dim=", np.shape(y),"z dim=", np.shape(z))


x dim= (10, 5) y dim= (10, 5) z dim= (10, 5)


In [17]:
#b.
x, y = np.ogrid[:10, :5]
z = x + y 

print("x dim=", np.shape(x), "y dim=", np.shape(y),"z dim=", np.shape(z))


x dim= (10, 1) y dim= (1, 5) z dim= (10, 5)


#Question_3\
For np.ogrid only one dimension of each returned array is greater than 1.
And np.mgrid returns a dense mesh-grid when indexed, so that each returned argument has the same shape.